### ISSUE TITLE
United-atom Mie lambda-6 viscosities

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#1]
We are simulating the normal and branched alkanes to determine the adequacy of the united-atom Mie lambda-6 potential to predict viscosity. Although the ultimate goal is to predict high pressure viscosities, currently we are investigating the ability to predict saturation viscosity. In order to account for uncertainties in the parameter set (epsilon/sigma) for a given lambda, we have performed a Bayesian MCMC uncertainty analysis.

The figure below shows the feasible CH3 parameter sets for different values of lambda:

![image](https://user-images.githubusercontent.com/23408516/39202474-3f85d1d8-47af-11e8-8ec7-68bc3d19ad66.png)

This figure shows the percent deviations in liquid density and vapor pressure for the different parameter sets:

![image](https://user-images.githubusercontent.com/23408516/39202770-269a44c8-47b0-11e8-8031-40de35b6e7a9.png)

As we can see, the 15-6 or 16-6 potential appear to be the best options for predicting VLE.

We then simulate a subset of these epsilon/sigma parameter sets to determine the overall uncertainty in viscosity for a given lambda.

Here are the viscosity results for ethane (just lambda =13-16), where the error bars represent the distribution in epsilon/sigma sets:

![image](https://user-images.githubusercontent.com/23408516/39202657-c566f084-47af-11e8-9b6d-af78d2031239.png)

Clearly, the viscosity is over-predicted with the UA Mie potential, and the bias increases with increasing lambda. Although the 13-6 potential is better at predicting viscosity, recall that it is significantly worse at predicting VLE than the 15-6 or 16-6. In other words, there is a significant trade-off between accurate prediction of VLE and accurate prediction of viscosity. This suggests that we need an alternative (perhaps all-atom) model to accurately predict both VLE and viscosity.

We are repeating this analysis now for propane, butane, and n-octane where we include the uncertainty in the CH2 parameters.

**Comment by mostafa-razavi** [comment]
@ramess101 
Results of Mie n-butane when n=16 is attached. Do we have a script to generate the above plot, i.e. the viscosity deviation from Refprop vs temperature? I also attach the text files containing the data:

![gk_mcmc_all_rho0](https://user-images.githubusercontent.com/16358113/39689986-91008ec6-51a6-11e8-99db-4649d710c93e.png)
![gk_mcmc_all_rho1](https://user-images.githubusercontent.com/16358113/39689987-911c2870-51a6-11e8-968a-935b8fbc8950.png)
![gk_mcmc_all_rho2](https://user-images.githubusercontent.com/16358113/39689989-9133df88-51a6-11e8-923e-13e20dd97f2b.png)
![gk_mcmc_all_rho3](https://user-images.githubusercontent.com/16358113/39689990-91590de4-51a6-11e8-8a53-3498597283b6.png)
![gk_mcmc_all_rho4](https://user-images.githubusercontent.com/16358113/39689991-91971256-51a6-11e8-825b-52a961bfe9a7.png)

[Results_Mie_16_Bayesian_Viscosity_200_MCMC.zip](https://github.com/ramess101/IFPSC_10/files/1978896/Results_Mie_16_Bayesian_Viscosity_200_MCMC.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

Yes, I have a script but I will clean it up before I post it.

**Comment by ramess101** [comment]
@mostafa-razavi 

OK, I have uploaded "compare_TDE_REFPROP.py" that compares the simulations with the REFPROP correlation and TDE experimental data. The header for this file explains what files you need to call it. I have also made it so that it will be called automatically in the future after GreenKubo_analyze.py.

*** Note that I have created new files called "nAlkanes_SaturatedViscosity" and "branchedAlkanes_SaturatedViscosity". These files will use the native Lennard-Jones function in Gromacs if the force field is a 12-6 potential (this is about twice as fast as tabulated potential). Also, note that I also renamed some directories. Specifically, "$Compound"/Gromacs/Tabulated is now just "$Compound"/Gromacs/Gromacs_input because the .gro and .top files are the same for tabulated and Lennard-Jones.  ***

**Comment by ramess101** [comment]
@mostafa-razavi 

This is what you should get with the files you sent me for 16-6 MCMC:

![image](https://user-images.githubusercontent.com/23408516/39718111-874745e0-51f2-11e8-88da-a916a6aad015.png)

Note that the large uncertainty at low Tsat appears to be a bug in my bootstrap analysis code. We will need to work on that, but it does not change the primary conclusion that the Mie 16-6 potential actually under predicts viscosity for butane!

This is consistent with what I get for 16-6 MCMC for propane:

![image](https://user-images.githubusercontent.com/23408516/39718163-ba4af270-51f2-11e8-8bc2-5cb37f98804c.png)

And for propane with Potoff:

![image](https://user-images.githubusercontent.com/23408516/39718227-e6090b7c-51f2-11e8-8bfe-db8c7b9cd650.png)

Note that the abnormal value at 210 K is likely because of data analysis as well. We will figure that out, but for now it is good enough.

This is very curious that the 16-6 is actually under predicting viscosity. 

The 14-6 (TAMie, which is also an AUA model) appears to under predict viscosity to an even higher degree:

![image](https://user-images.githubusercontent.com/23408516/39722790-f94aec60-5200-11e8-8cc4-dd945dcbb716.png)

This explains, in part, why Gordon reported a 20-6 CH2 potential for n-alkanes when trying to reproduce viscosity data.

**Comment by ramess101** [comment]
@mostafa-razavi 

OK, so this under prediction is actually fairly well-documented. It is a result of the united-atom approach. Gordon argued that you can change the repulsive exponent to overcome this issue, but his VLE results were worse. We have shown that for adequate VLE the viscosity will still be under predicted. Ethane appears to be an exception.

Gordon provided some results for n-alkanes using the TraPPE model (open circles):

![image](https://user-images.githubusercontent.com/23408516/39719598-ef0ac7de-51f6-11e8-8b5d-5d6291dfc699.png)

I am currently running TraPPE for propane, but it would be good to get TraPPE for butane finished so we can make a comparison. I will start TraPPE for butane unless your Potoff runs finish before mine, since you have done all the other butane runs.

One important question is the impact of fixed bonds. We are using constraints while Gordon used LAMMPS, so his larger compounds could not be constrained and he never explicitly says if his smaller compounds are constrained or what bond potential he is using.

**Comment by mostafa-razavi** [comment]
@ramess101 Here is the Potoff butane three lower densities that finished. I'll run the other two densities again to complete this. 

@ramess101 I updated the plot to include rho3 and rho4.

![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40063462-5deb93e2-582b-11e8-9bcf-126306ca231d.png)


> Note that the large uncertainty at low Tsat appears to be a bug in my bootstrap analysis code. We will need to work on that, but it does not change the primary conclusion that the Mie 16-6 potential actually under predicts viscosity for butane!

Is this problem solved?

**Comment by ramess101** [comment]
@mostafa-razavi 

Those results look good. 

> Is this problem solved?

No. Sorry, not high on my priority list. But it should be.

**Comment by ramess101** [comment]
@mostafa-razavi 

Try using "GreenKubo_analyze" now to analyze the low density Potoff butane run. I merged the GreenKubo_analyze_fitw8.py code and modified it to run faster. This is only a minor fix, but if this doesn't improve the results I have a couple other things I can try.

**Comment by ramess101** [comment]
@mostafa-razavi 

I think that it might be important to look at the viscosity trend approaching the triple point. For example, while the Potoff model does fairly well at these moderate viscosities (between 0.1 and 1 cP), I am curious what it looks like for 1 to 10 cP. I was thinking about including simulation conditions for propane at T= 90, 100, 110, 120, and 130 K. Recall that these were the Potoff propane results between 160 and 320 K:

![image](https://user-images.githubusercontent.com/23408516/39894749-1f6af30c-5465-11e8-8dd3-c2854f7d665a.png)

What do you think?

**Comment by ramess101** [comment]
@mostafa-razavi 

Here are the Potoff propane results at lower T. I am surprised that it works as well as it does.  I should probably use more replicates since the uncertainties get quite large.

![image](https://user-images.githubusercontent.com/23408516/39906728-b3f0d2da-54a1-11e8-8aed-3ab2830eeee0.png)

However, recall that these simulations are performed at the REFPROP Tsat and rholsat. I am assuming that each force field gives a reasonable rholsat.

**Comment by ramess101** [comment]
@mostafa-razavi 

The N=200 octane TraPPE results are finished.

![image](https://user-images.githubusercontent.com/23408516/39926602-e6bd801e-54ec-11e8-9f5b-bde0d373761f.png)

It will be interesting to see how much better the Potoff model does. Note that I only used 30 replicates at the lowest temperature, while the rest had 40. This can partially explain the large uncertainty. Also, using a larger system size should decrease the uncertainties. But the real reason for these large uncertainties is still the GreenKubo analysis. It is really not a bug, we just need to discuss how we want to compute the uncertainties. Right now, it allows for the cut-off time to be a random variable, which can occasionally lead to abnormal viscosity values.

For example, this is the distribution of bootstrapped viscosities at the two lowest T:

T=256 K:

![image](https://user-images.githubusercontent.com/23408516/39926703-3de5935e-54ed-11e8-8517-be3f412d573e.png)

T = 321 K

![image](https://user-images.githubusercontent.com/23408516/39926734-5483e476-54ed-11e8-9c39-c2c8c622702b.png)


Clearly, most of the values are in the higher viscosity region for T=256 K. But, there is a second mode at lower viscosities. This mode is very pronounced for T=321 K. If we used a constant cut-off this would likely not be the case (I can test this quite easily).

For a comparison, this is what the distributions look like at the higher temperatures:

![image](https://user-images.githubusercontent.com/23408516/39927274-ee8b1fd4-54ee-11e8-9332-9e3c927725c2.png)

![image](https://user-images.githubusercontent.com/23408516/39927290-f9d2b064-54ee-11e8-8fcc-c94e2335b8ca.png)

![image](https://user-images.githubusercontent.com/23408516/39927306-043d94e2-54ef-11e8-8b38-8d1cd8bc2593.png)

**Comment by ramess101** [comment]
@mostafa-razavi 

I created a script called compare_force_fields that produces a plot for multiple compounds and force fields. These are the results for n-alkanes that I have compiled so far. It is incomplete, but already starting to paint a clear picture that Potoff does a lot better than TraPPE and slightly better than TAMie:

![image](https://user-images.githubusercontent.com/23408516/40135480-b52c2482-5902-11e8-9d40-bd86f20607cf.png)

**Comment by ramess101** [comment]
@mostafa-razavi 

I performed some non-saturation simulations with the Potoff potential for propane. As expected, the viscosity is over predicted for the higher densities. However, if we plot the viscosity with respect to pressure it actually agrees very nicely. Note that the REFPROP correlation is only valid to 1000 MPa, so we do not really know if that highest point is good or not. I will run some simulations below 1000 MPa to see if the Potoff model is actually reliable enough for this case.

![image](https://user-images.githubusercontent.com/23408516/40082386-19212416-584e-11e8-9344-4aaa50b4dec4.png)

**Comment by ramess101** [comment]
@mostafa-razavi 

I performed four more points with Potoff propane at high densities:

![image](https://user-images.githubusercontent.com/23408516/40094778-25de667c-5886-11e8-8bb2-1b06373e9c8f.png)

Clearly something is wrong with the uncertainty for the 1000 MPa point, but it is rather remarkable that the Mie 16-6 potential works so well up to 700 MPa.

I now have the TraPPE propane runs going.

**Comment by ramess101** [comment]
@mostafa-razavi 

These are the TraPPE propane results:

![image](https://user-images.githubusercontent.com/23408516/40120896-849fffb6-58dd-11e8-9689-e9af0553547c.png)

So the Potoff model is much better at predicting even high pressure viscosities. However, both models are deficient when plotted with respect to density.

**Comment by ramess101** [comment]
@mostafa-razavi 

I have a new GreenKubo_analyze code that is more robust in assigning uncertainties. For example, here I have rerun the bootstrap uncertainty at P around 700 and 1000 MPa, which previously had very large uncertainties:

![image](https://user-images.githubusercontent.com/23408516/40140994-93746408-5911-11e8-9947-e2f3b6ff0b15.png)

I am currently reprocessing the other points. Moving forward make sure to use the new GreenKubo_analyze script.

**Comment by mostafa-razavi** [comment]
@ramess101 
## Potoff-C4-N200
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40187509-ae1ae3c2-59c5-11e8-909e-ab4b7196d2c9.png)

[Potoff-C4-N200.zip](https://github.com/ramess101/IFPSC_10/files/2013820/Potoff-C4-N200.zip)

**Comment by mostafa-razavi** [comment]
@ramess101 
## Potoff-C4-N800
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40187789-64a0f2bc-59c6-11e8-9d1f-f5e9bc7764ec.png)
[Potoff-C4-N800.zip](https://github.com/ramess101/IFPSC_10/files/2013840/Potoff-C4-N800.zip)

**Comment by mostafa-razavi** [comment]
@ramess101 
## TraPPE-C4-N400

![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40188091-23973118-59c7-11e8-80c7-dfdb8cdd2bb1.png)

[TraPPE-C4-N400.zip](https://github.com/ramess101/IFPSC_10/files/2013846/TraPPE-C4-N400.zip)

**Comment by mostafa-razavi** [comment]
@ramess101 
## TAMie-C4-N400

![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40188178-596596fe-59c7-11e8-8caf-b445c66d474e.png)
[TAMie-C4-N400.zip](https://github.com/ramess101/IFPSC_10/files/2013858/TAMie-C4-N400.zip)

**Comment by mostafa-razavi** [comment]
@ramess101 
## TraPPE-IC4H10-N800
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40252515-86d8a214-5aaa-11e8-9122-12dd87068a21.png)
[TraPPE-IC4H10-N800.zip](https://github.com/ramess101/IFPSC_10/files/2018260/TraPPE-IC4H10-N800.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

Wow, those uncertainties are very small for TraPPE IC4H10 N800 (compared to what we usually see where the uncertainy is +- 5 %). I would assume this is because of the larger system size, but previously in Issue #5 the N800 uncertainties were not consistently smaller. The results in Issue #5 used the old GreenKubo_analyze, so maybe now with the better GreenKubo_analyze the uncertainties are consistently smaller for larger systems. 

**Correction, since viscosity is a collective property the uncertainties do not depend on the number of molecules.

**Comment by mostafa-razavi** [comment]
## TraPPE-IC5H12-N400
@ramess101 There seems to be a problem in TDE data, namely there are two trends that are significantly different. What do you think?

![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40322198-97766ee2-5cff-11e8-8a94-390d1e1ca815.png)

[TraPPE-IC5H12-N400.zip](https://github.com/ramess101/IFPSC_10/files/2023576/TraPPE-IC5H12-N400.zip)

**Comment by mostafa-razavi** [comment]
## TraPPE-IC6H14-N400
@ramess101 
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40322674-2540beac-5d01-11e8-8b33-b42391d49374.png)
[TraPPE-IC6H14-N400.zip](https://github.com/ramess101/IFPSC_10/files/2023626/TraPPE-IC6H14-N400.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

> There seems to be a problem in TDE data, namely there are two trends that are significantly different. What do you think?

I trust the TDE data that agree closely with the REFPROP correlation. The % error for TraPPE appears to be consistent, namely, 20 to 50 % under prediction that increases at lower temperatures.

**Comment by ramess101** [comment]
@mostafa-razavi 

Here are the n-butane high pressure results. Note that the REFPROP correlation is only recommended up to 200 MPa (700 kg/m3).

Potoff:

![image](https://user-images.githubusercontent.com/23408516/40667692-fd1c8d0a-631f-11e8-8922-47c7f3ac2510.png)

TraPPE:

![image](https://user-images.githubusercontent.com/23408516/40667703-03a46b5c-6320-11e8-8ba9-9ffa8abcaaf2.png)

Again, we see that the Potoff potential over predicts viscosity at high densities. Because of the large uncertainties in REFPROP above 200 MPa, it is difficult to ascertain whether or not the Potoff model is unreliable at high pressures. Clearly, the TraPPE model under predict viscosities at all conditions, and appears to get slightly worse at higher pressures.

**Comment by mostafa-razavi** [comment]
## TAMie-C8H18-N800 
@ramess101 
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40670190-bfc3bea8-6336-11e8-8b39-c59b37125136.png)
[TAMie-C8-N800.zip](https://github.com/ramess101/IFPSC_10/files/2049080/TAMie-C8-N800.zip)

(Updated using Rerun_Green_Kubo script)
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/41160931-1bb2108c-6aff-11e8-85d1-e094f0d6adbe.png)
[TAMie-C8H18-N800.zip](https://github.com/ramess101/IFPSC_10/files/2084551/TAMie-C8H18-N800.zip)

**Comment by mostafa-razavi** [comment]
## TraPPE-IC8H18-N400
@ramess101 
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40670540-8c8f087a-6337-11e8-960d-c28ab3c1b668.png)
[TraPPE-IC8H18-N400.zip](https://github.com/ramess101/IFPSC_10/files/2049106/TraPPE-IC8H18-N400.zip)

**Comment by mostafa-razavi** [comment]
## TAMie-IC4H10-N400?
@ramess101 Could you confirm if ran the right script for this simulation? I would expect TAMie to do better than this. Right?

![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40820953-a64bb618-6531-11e8-95fb-d8b419c4fee8.png)
[TAMie-IC4H10-N400.zip](https://github.com/ramess101/IFPSC_10/files/2060983/TAMie-IC4H10-N400.zip)

Update: (2/7/2018)
## TAMie-IC4H10-N400 
@ramess101 @Kaiveria Here is what I get from the new simulation. It's very close to TraPPE but slightly different. You might want to run one of these points on your computer to see if my simulation is correct or not.
![compare_tde_refprop_sat](https://user-images.githubusercontent.com/16358113/42185935-eead38ac-7e07-11e8-9a54-bdc23bbfd268.jpg)
[compare_TDE_REFPROP_sat.pdf](https://github.com/ramess101/IFPSC_10/files/2156773/compare_TDE_REFPROP_sat.pdf)
[TAMie-IC4H10-N400.zip](https://github.com/ramess101/IFPSC_10/files/2156774/TAMie-IC4H10-N400.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

Those results look almost identical to the TraPPE results. I can take a closer look, but I am pretty confident these are not the TAMie results.

**Comment by ramess101** [comment]
@mostafa-razavi 

Your "IC4H10_job_2018_05_23_18_37_17" file says that you submitted TAMie. However, the only way to be certain is to find the IC4H10.top file, which should be at IC4H10/Gromacs/Saturation_Viscosity/TAMie_N400/MCMC_x/IC4H10.top. Can you post that file?

Also, these are the parameters you should have:

[ atomtypes ]
; _O indicates the (pseduo)atom is bonded to an oxygen. _C indicates the
; (pseudo)atom is bonded to a carbon.
; name      bond_type    mass       charge   ptype   C6        Clam
  CH3_C     CH3          15.03450   0.000    A       0.00819752345327 2.33014239486e-06; [CH3]-CHX
  CH2_C     CH2          14.02660   0.000    A       0.00631986287433 4.48496002146e-06; (CHX)2-[CH2]
  CH_C      CH           13.01900   0.000    A       0.002764768497 3.64762596488e-06; (CHX)3-[CH]
  C_C       C            12.01100   0.000    A       0.002764768497 3.64762596488e-06; (CHX)4-[C]

[ nonbond_params ]
; i j func C6 Clam
CH3_C CH2_C 1 0.00726864063375 3.3075463302e-06; cross-interactions for CH3_C and CH2_C
CH3_C CH_C 1 0.00489378022934 3.10910301117e-06; cross-interactions for CH3_C and CH_C
CH3_C C_C 1 0.00489378022934 3.10910301117e-06; cross-interactions for CH3_C and C_C
CH2_C CH_C 1 0.00419893969751 4.08742151221e-06; cross-interactions for CH2_C and CH_C
CH2_C C_C 1 0.00419893969751 4.08742151221e-06; cross-interactions for CH2_C and C_C
CH_C C_C 1 0.00419893969751 4.08742151221e-06; cross-interactions for CH_C and C_C

**Comment by mostafa-razavi** [comment]
@ramess101 
[IC4H10.top.txt](https://github.com/ramess101/IFPSC_10/files/2063823/IC4H10.top.txt) is one of the files you asked for. It seems to be identical to the values you posted above. Could there be a problem with  the [compare_TDE_REFPROP.py.txt](https://github.com/ramess101/IFPSC_10/files/2063840/compare_TDE_REFPROP.py.txt) script that I used? I used this old version because, the original 
[compare_TDE_REFPROP.py.txt](https://github.com/ramess101/IFPSC_10/files/2063843/compare_TDE_REFPROP.py.txt) script in the "Script" folder give me an error about not having a value for MW for that compound in 
```
Mw_list = {'C3H8':44.096,'C4H10':58.122}
```

**Comment by ramess101** [comment]
@mostafa-razavi 

I don't think the compare_TDE_REFPROP.py file is the problem, because the eta_fit_rho0, etc. figures also look like the TraPPE results. Is it possible that you called GreenKubo_analyze from the wrong directory somehow? The script should do this automatically, but it could be an issue if you had to call it manually for some reason.

**Comment by mostafa-razavi** [comment]
## TraPPE-IC8H18-N200
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/40997320-36831f7a-68d2-11e8-907b-be632141976f.png)
[TraPPE-IC8H18-N200.zip](https://github.com/ramess101/IFPSC_10/files/2073640/TraPPE-IC8H18-N200.zip)

**Comment by mostafa-razavi** [comment]
## TAMie-IC5H12-N400
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/41019228-c648b1c0-692b-11e8-867f-cb4edf919275.png)
[TAMie-IC5H12-N400.zip](https://github.com/ramess101/IFPSC_10/files/2074920/TAMie-IC5H12-N400.zip)

**Comment by ramess101** [comment]
This plot compares Potoff, TraPPE, and TAMie for propane at 293 K and high pressures:

![image](https://user-images.githubusercontent.com/23408516/41156825-c1c00340-6ae0-11e8-9924-2cd165ca4f58.png)

**Comment by mostafa-razavi** [comment]
## TAMie-IC6H14-N400
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/41130561-5976d7d8-6a85-11e8-92d7-50f7a8e11447.png)
[TAMie-IC6H14-N400.zip](https://github.com/ramess101/IFPSC_10/files/2082344/TAMie-IC6H14-N400.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

These all look really good. I am still confused about TAMie-IC4H10 that looked almost exactly like TraPPE-IC4H10. We need to figure that out at some point, or we can just rerun it sometime.

Mostafa, for your next simulations, could you run C4H10 and C8H18 at high pressures (T293highP) for the TAMie force field? You can use the "nAlkanes_T293highPViscosity" file. (We have some better scripts for branched alkanes that are more robust, but we are still testing to make sure they work well.) Right now the nAlkanes_T293highPViscosity script is set up to run C4H10 with TAMie for the 5 T293highP state points, so you shouldn't need to change much. Let me know if you have any issues with the script though.

**Comment by ramess101** [comment]
@mostafa-razavi 

I just wanted to see if you were able to get the T293highP viscosities running for C4H10 and C8H18 with TAMie. I am currently out of town, so please ask @Kaiveria if you have any questions with the scripts. Thanks

**Comment by mostafa-razavi** [comment]
## TraPPE-IC8H18-N800
![compare_tde_refprop](https://user-images.githubusercontent.com/16358113/41441947-f50f99c8-7002-11e8-9569-a73ac3c3e641.png)
[TraPPE-IC8H18-N800.zip](https://github.com/ramess101/IFPSC_10/files/2104244/TraPPE-IC8H18-N800.zip)

**Comment by mostafa-razavi** [comment]
> I just wanted to see if you were able to get the T293highP viscosities running for C4H10 and C8H18 with TAMie. I am currently out of town, so please ask @Kaiveria if you have any questions with the scripts. Thanks

@ramess101 Right now I'm running TAMie_C4H10_N400_T293highP. One of the computers that I'm using is under maintenance and I do not have access to it. I will check if I can use our other computers to run TAMie_C8H18_N400_T293highP.

**Comment by mostafa-razavi** [comment]
## TAMie-C4H10-N400-T293highP
![compare_refprop_t293highp](https://user-images.githubusercontent.com/16358113/41579442-fd79d866-7364-11e8-83d7-4c4667e1adcc.jpg)
[compare_REFPROP_T293highP.pdf](https://github.com/ramess101/IFPSC_10/files/2114008/compare_REFPROP_T293highP.pdf)
[TAMie_C4H10_N400_T293highP.zip](https://github.com/ramess101/IFPSC_10/files/2114009/TAMie_C4H10_N400_T293highP.zip)

**Comment by mostafa-razavi** [comment]
## TAMie_C8H18_N400_T293highP
@ramess101 Do we have any experimental data to complete the following plot?
![compare_refprop_t293highp](https://user-images.githubusercontent.com/16358113/41998688-52f05462-7a29-11e8-9e10-dea4eb6384bc.jpg)
[compare_REFPROP_T293highP.pdf](https://github.com/ramess101/IFPSC_10/files/2142860/compare_REFPROP_T293highP.pdf)
[TAMie_C8H18_N400_T293highP.zip](https://github.com/ramess101/IFPSC_10/files/2142859/TAMie_C8H18_N400_T293highP.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

> Do we have any experimental data to complete the following plot?

Yes we do. When I create the final figures the data will be included.

I think we have completed all of the simulations that are currently on the work plan Issue #9 (at least those that really need to be run). We have a few more molecules that should be added, so check back on Issue #9 by tomorrow for the next batch to run. Also, it is very important that you double check that you have the most recent .top files. We just discovered a typo that impacts the larger branched alkanes (IC5, IC6, IC8).

**Comment by ramess101** [comment]
@mostafa-razavi 

I just realized that you are already running the Mie 16-6 MCMC for n-octane. This is probably not the best use of computational resources. I don't think we are actually going to include the Mie MCMC results in our manuscript. So I would probably kill them (unless they are nearly finished) once we have selected the next system to run.

**Comment by mostafa-razavi** [comment]
## TraPPE-C12H26-N400 
##### (Number of Replicates: 48, Duration: 2 days and 6 hrs, on 24 cores)
![compare_tde_refprop_sat](https://user-images.githubusercontent.com/16358113/42394105-2da9c140-8116-11e8-9776-17c8c5588933.jpg)
[compare_TDE_REFPROP_sat.pdf](https://github.com/ramess101/IFPSC_10/files/2171540/compare_TDE_REFPROP_sat.pdf)
[TraPPE-C12H26-N400.zip](https://github.com/ramess101/IFPSC_10/files/2171541/TraPPE-C12H26-N400.zip)

**Comment by mostafa-razavi** [comment]
### TraPPE-3MPentane-N400
![compare_tde_refprop_sat](https://user-images.githubusercontent.com/16358113/42468252-91c7081a-8371-11e8-99df-54a5a897c67a.jpg)
[compare_TDE_REFPROP_sat.pdf](https://github.com/ramess101/IFPSC_10/files/2177499/compare_TDE_REFPROP_sat.pdf)
[TraPPE-3MPentane-N400.zip](https://github.com/ramess101/IFPSC_10/files/2177500/TraPPE-3MPentane-N400.zip)

**Comment by mostafa-razavi** [comment]
## TraPPE-IC5H12-N400 
![compare_refprop_t293highp](https://user-images.githubusercontent.com/16358113/42600417-741bed26-851f-11e8-8dd6-a9ffed45a576.jpg)
[compare_REFPROP_T293highP.pdf](https://github.com/ramess101/IFPSC_10/files/2186247/compare_REFPROP_T293highP.pdf)
[TraPPE-IC5H12-N400.zip](https://github.com/ramess101/IFPSC_10/files/2186248/TraPPE-IC5H12-N400.zip)

**Comment by mostafa-razavi** [comment]
## TraPPE-3MPentane-N400-T293highP
![compare_refprop_t293highp](https://user-images.githubusercontent.com/16358113/42713904-5b8c53e6-86ae-11e8-9d99-a20bdc25a675.jpg)
[compare_REFPROP_T293highP.pdf](https://github.com/ramess101/IFPSC_10/files/2194179/compare_REFPROP_T293highP.pdf)
[TraPPE-3MPentane-N400-T293highP.ZIP](https://github.com/ramess101/IFPSC_10/files/2194180/TraPPE-3MPentane-N400-T293highP.ZIP)

**Comment by mostafa-razavi** [comment]
## Potoff-IC6H14-N400
![compare_tde_refprop_sat](https://user-images.githubusercontent.com/16358113/42787852-9c24d94c-8919-11e8-961f-8f25e1bef939.jpg)
[compare_TDE_REFPROP_sat.pdf](https://github.com/ramess101/IFPSC_10/files/2199581/compare_TDE_REFPROP_sat.pdf)
[Potoff-IC6H14-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199582/Potoff-IC6H14-N400.zip)

**Comment by mostafa-razavi** [comment]
##  Potoff-C12H26-N400-rc14
![compare_tde_refprop_sat](https://user-images.githubusercontent.com/16358113/42963903-bfe364f8-8b52-11e8-803d-965a0fc60b9f.jpg)
[compare_TDE_REFPROP_sat.pdf](https://github.com/ramess101/IFPSC_10/files/2211300/compare_TDE_REFPROP_sat.pdf)
[Potoff-C12H26-N400-rc14.zip](https://github.com/ramess101/IFPSC_10/files/2211301/Potoff-C12H26-N400-rc14.zip)

**Comment by ramess101** [comment]
Hallelujah! This is awesome @mostafa-razavi . So this really was a cut-off issue for the larger alkanes. 

@Kaiveria 

Can you prepare the C22 (or whatever the next REFPROP compound is C20 maybe?) files for Mostafa to run? Specifically, we need the N400 boxsizes for saturation. This could be really useful. Mostafa can start TraPPE and we will run Potoff and TAMie once we have some cores free.

**Comment by mostafa-razavi** [comment]
Is C16 running? Does using packmol instead of Gromacs for initiating
simulations help?

**Comment by ramess101** [comment]
@mostafa-razavi 

Yes, we already finished all the C16 results. They looked good.

No, we didn't need packmol. The cut-off was the real issue. If Gromacs fails to build C20/C22 @Kaiveria will let you know.

**Comment by mostafa-razavi** [comment]
@ramess101 How can the cutoff be an issue? I thought your TraPPE-C16 with rcut=1.4 nm failed, too. Right?

**Comment by ramess101** [comment]
@mostafa-razavi 

TraPPE-C16 did run successfully. I think we misspoke previously that it did not work. Potoff was the only one that failed. Using a 1.0 nm cut-off molecules don't feel any force and then suddenly feel a fairly strong force when they move closer. This is very problematic for flexible molecules that will feel non-bonded within the same chain. Does that make sense?

**Comment by mostafa-razavi** [comment]
@ramess101 Hmmm... So this problem potentially exists even for rcut=1.4, but it's less likely. Right?

**Comment by ramess101** [comment]
@mostafa-razavi 

Yeah, there is always a small pulse in force when you cross from zero interaction to within the cut-off, but as you get to 1.4 nm the force is significantly smaller than at 1.0 nm. We are considering including this in a discussion/supporting information section of our manuscript.

**Comment by mostafa-razavi** [comment]
@ramess101 So this could be a demonstration for one of the reasons why force-smoothed potentials (switched-force or shifted-force) might be better. Do you think we should test this with a switched-force potential function?

**Comment by ramess101** [comment]
@mostafa-razavi 

It certainly is an example of where a switched-force/shifted, etc. potential would be better. I think we can test this quite easily. I am not sure we can get meaningful results before the deadline, mainly because we would need to reparameterize the switched-force to get the same viscosity as the cut-off. I think we can just mention this without proving it.

**Comment by Kaiveria** [comment]
@mostafa-razavi 
@ramess101 
Good afternoon. 
I have heard that a C22H46 TraPPE run is to be started soon. I have checked the C22H46 files and have successfully started a test run with 200 molecules, though it required changing the number of tries for insert-molecules in the AlkanesViscosity.sh script:

gmx insert-molecules -ci ../../../"$Compound".gro -nmol "$Nmol" -try 2000 -box "${liquid_box[j]}" "${liquid_box[j]}" "${liquid_box[j]}" -o "$Compound"_box.gro > insertout 2>> insertout

This used to specify "-try 500" for me which was not sufficient.
