### ISSUE TITLE
Rerun GreenKubo_analyze

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#13]
@mostafa-razavi @Kaiveria 

Now that we have resolved the main issues in GreenKubo_analyze it is important for us to go back and reprocess the data. The three step process is simple:

1) Make sure you have the most recent version of GreenKubo_analyze.py
2) Edit the parameters in Rerun_Green_Kubo_Analyze.sh (e.g., Compound, Model, Conditions...) for the given system you want to reanalyze
3) Execute Rerun_Green_Kubo_Analyze.sh

The Rerun_Green_Kubo_Analyze.sh script currently has the parameters for rerunning IC8H18 for TAMie with N400. The error bars on this simulation have the problem that we have fixed in GreenKubo_analyze. So @mostafa-razavi could you reprocess this system and post your results this week? Eventually you will want to reprocess all of your results, but in the immediate future I just need this system for a presentation I am giving at the NIST TRC Consortium.

**Comment by ramess101** [comment]
@mostafa-razavi 

Note that we have created a directory IFPSC_10/Results where we have placed the results that you posted on GitHub in Issue #1 . Once you have rerun the GreenKubo analysis for these systems, simply upload the updated results in the respective folder. Notice that, for storage purposes, we only need/want the GK_eta_boots_rhoX files on GitHub.

**Comment by mostafa-razavi** [comment]
>  So @mostafa-razavi could you reprocess this system and post your results this week? 

@ramess101 I don't think I ever simulated TAMie-IC8H18-N400. I just checked and it's not in the Work Plan list either. Did you mean TraPPE-IC8H18-N400?

**Comment by ramess101** [comment]
@mostafa-razavi 

Sorry, you are correct, there is no IC8H18 for TAMie because TAMie does not have parameters for C. What I meant was TAMie-C8H18-N400.

**Comment by mostafa-razavi** [comment]
>Sorry, you are correct, there is no IC8H18 for TAMie because TAMie does not have parameters for C. What I meant was TAMie-C8H18-N400.

I don't have TAMie-C8H18-N400 either. What I simulated was TAMie-C8H18-N800. I think N=800 was the default value of N in C8H18_Nmol file. I only realized after the simulation was done. I will reprocess TAMie-C8H18-N800 and let you know.

**Comment by ramess101** [comment]
@mostafa-razavi 

OK, thanks. N800 and N400 should give the same result, so the only real difference is how long the simulations take. So reprocessing the N800 data would be great.

**Comment by mostafa-razavi** [comment]
I uploaded the results of Rerun_Green_Kubo_Analyze for TAMie-C8H18-N400

**Comment by ramess101** [comment]
@mostafa-razavi 

OK, thanks. From a quick glance at the files you posted, it looks like the average viscosity is still about the same as before and the uncertainties look better.

**Comment by mostafa-razavi** [comment]
@Kaiveria @ramess101
Michelle, attached are the rerun results for the compounds/models that you requested. Let me know if there is an issue.

[7-16-TAMie-IC6H14-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199546/7-16-TAMie-IC6H14-N400.zip)
[7-16-TAMie-IC5H12-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199547/7-16-TAMie-IC5H12-N400.zip)
[7-16-TraPPE-C12H26-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199548/7-16-TraPPE-C12H26-N400.zip)
[7-16-TAMie-C8H18-N800.zip](https://github.com/ramess101/IFPSC_10/files/2199549/7-16-TAMie-C8H18-N800.zip)
[7-16-TraPPE-IC6H14-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199550/7-16-TraPPE-IC6H14-N400.zip)
[7-16-TAMie-C4H10-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199551/7-16-TAMie-C4H10-N400.zip)
[7-16-TraPPE-C4H10-N400.zip](https://github.com/ramess101/IFPSC_10/files/2199552/7-16-TraPPE-C4H10-N400.zip)

**Comment by ramess101** [comment]
@mostafa-razavi 

Awesome! @Kaiveria will look over these tomorrow and let you know.

**Comment by mostafa-razavi** [comment]
@ramess101 Any urgent simulations?

**Comment by ramess101** [comment]
@mostafa-razavi 

If you have cores free, then yes! 

We need to rerun C12H26, saturation, N400, LINCS, with the Potoff potential. We ran these before, but we think that the 1.0 nm cut-off caused some erroneous results. So could you rerun C12 saturation Potoff using a 1.4 nm cut-off instead? This will require you to manually modify the AlkanesViscosity.sh file (approximately line 204):

`###Cut-off distance is different for some force fields
if [ "$Model" = 'Potoff' ]
then

rvdw=1.0 # [nm]

else

rvdw=1.4 # [nm]

fi
`

Change rvdw=1.0 to rvdw=1.4 for these Potoff runs.

NPT and OVERRIDE_STEPS should still be NO.

**Comment by Kaiveria** [comment]
@mostafa-razavi 

Wonderful. Thank you very much. This takes care of most of the problems. There are still a few lingering issues.
Rerunning GK did not fix the poor fits for state points 0 and 1 for C12H26 TraPPE saturation. They are quite bad so something more drastic may need to be done. IC8 TraPPE saturation and 3MPentane T293highP TraPPE have some similar lingering problems. I believe 3MPentane was run since the list of problems was emailed and I think I may have forgotten to mention IC8 in that list (sorry).
The initial guesses for the fitting or the cutoff time will probably have to be changed to get good behavior from these (as mentioned in last week's email). 
Many thanks again.

**Comment by ramess101** [comment]
@Kaiveria 

> Rerunning GK did not fix the poor fits for state points 0 and 1 for C12H26 TraPPE saturation. They are quite bad so something more drastic may need to be done. 

I actually like the fit for rho1. I think it adequately excludes the noise of the long-time tail. Do you think rho0 will be fixed by just forcing it to include all the data or by changing the guess?

**Comment by Kaiveria** [comment]
@ramess101 
I defer to your tail-spotting abilities on point 1. I do think point 0 could probably be made better by a different guess or by forcing a longer fitting interval, but we may not want to do that.
