### ISSUE TITLE
RDFs

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#15]
To demonstrate why the Mie 16-6 model over-estimates viscosity at high densities at 293 K but not at the triple point, we are investigating the RDFs of propane at these two state points:

![image](https://user-images.githubusercontent.com/23408516/42850485-194b96b0-89e5-11e8-85d9-30f0e754368f.png)

Clearly, the high pressure simulation has much closer CH3 and CH2 interactions. We are working on making these look a little prettier.  @Kaiveria can you make the CH3 x CH2 RDF as well?

**Comment by mostafa-razavi** [comment]
@ramess101 @Kaiveria 
Interesting. I wonder how the same plot looks like for a 12-6 potential. Do we have data to plot that?

**Comment by ramess101** [comment]
@mostafa-razavi 

Good point. We should probably include the TraPPE and TAMie RDFs at the same state points.

@Kaiveria can you replicate the Potoff RDF simulations with the TraPPE and TAMie force fields? Thanks!

**Comment by ramess101** [comment]
This plot shows the RDFs at three different state points:

1. Triple point (T and rho)
2. Triple point rho but T = 293
3. T =293 and very high density

![image](https://user-images.githubusercontent.com/23408516/43167023-9b92c6aa-8f55-11e8-992b-81c58b0ff9c1.png)

Note that increasing temperature causes a significant shift in the RDFs. Increasing density just increases the frequency of short-range interactions. Also, note that each force field is affected in the same manner but the impact on pressure and viscosity is largest for the 16-6 potential, since it is steepest.
