### ISSUE TITLE
Simulation time

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#20]
@mostafa-razavi 

I had not asked you previously to run simulations for the challenge compound because it did not seem necessary and there was no clear distinction between which jobs you or I should run (i.e. we aren't simulating various force fields). However, I am nervous about having enough computational resources to finish all the required simulations by the challenge deadline (10/7). The main reason for this problem is that at the highest pressures we need extremely long simulations, and sometimes I have to rerun those simulations because they were not long enough. I cannot simply overshoot with the simulation time because the post data analysis is also very slow as the file size becomes inordinately large. 

I am currently running simulations using 400 molecules, even though I know that a 200 molecule system would run about twice as fast and should not deviate considerably from the 400 molecule results. I would like to transition to a 200 molecule system, and I thought that it would make sense to include you in this effort.

Would you be able to simulate 224TMHexane with Potoff, 1.0 nm cut-off, 200 molecules, LINCS, 50-60 replicates, NPT first, for rho = 0 to 7? 

I will run rho = 8 to 12 (the higher pressure, long simulations). I need to update the GitHub repository files, so don't start running any simulations until I give you the go ahead.

Please let me know if you have any concerns

Thanks

**Comment by ramess101** [comment]
@mostafa-razavi 

All the files should be up to date now.

**Comment by mostafa-razavi** [comment]
@ramess101 
Excellent. Please let me know if there is more for me to do. I'm setting up the simulation now. I'll let you know if I have a question.

**Comment by ramess101** [comment]
@mostafa-razavi 

Great! Thanks! Let me know if you have any issues. And make sure to use the most recent "Gromacs_input", Scripts, and T293highP_Conditions files.

**Comment by mostafa-razavi** [comment]
@ramess101  Can you please quickly confirm this?
```
Compound=224TMHexane
Model=Potoff
Conditions_type=T293highP    #Saturation         #"$Model"_Saturation   #Saturation # ie T293highP
BondType=LINCS  #Harmonic (flexible) or LINCS (fixed)
Temp=293  # Default temp, used if no temperature file is found in conditions path
jlim=8  # Upper bound on j; condition sets to run; exclusive. Should usually be 5
jlow=0  # Lower bound on j; inclusive. needed in special cases. Should usually be 0
batches=4  # Number of batches to run
NREPS=15 #Run NREPS replicates in parallel/# in a batch (Overriden by NEMD=YES)
pin0=1  # Default pinoffset, used to tell taskset where to run jobs
nt_eq=1  # Thread number during equilibration
nt_vis=1  # This thread number will serve in production and viscosity runs
NPT=YES # YES indicates NPT runs should be carried out prior to NVT runs (YES or NO)
#echo "CHANGE THIS BACK BEFORE RUNNING MORE T293highP!!!"
NEMD=NO  # Calculate viscosity using the periodic perturbation method  (YES or NO)
RDF=NO  # Whether to perform RDF calculations (YES or NO)
MCMC_tors=NO # YES indicates model includes torsional uncertainties
#Set the number of molecules
Nmol=200
```

**Comment by mostafa-razavi** [comment]
@ramess101 
Potoff_224TMHexane_N200 for rho=0 to 7 is running based on the above script.

**Comment by ramess101** [comment]
This looks perfect

**Comment by ramess101** [comment]
@mostafa-razavi 

I fixed some bugs in the GreenKubo_analyze code for the bootstrap uncertainties. Please update your local copy.
